# cloudbuild.yaml
# Triggers Google Cloud Build CI pipeline
# Build history go to console https://cloud.google.com/build
#args: ['run', '-v', 'vol1:/home/app', '--rm', 'us-docker.pkg.dev/android-devrel-ci/us.gcr.io/android-build:tag1', '/bin/sh', '-c', 'cd /home/app && ./gradlew :app:lintProdRelease :app-nia-catalog:lintRelease :lint:lint']
steps:
  # Set a persistent volume according to https://cloud.google.com/cloud-build/docs/build-config (search for volumes)
  - id: 'ubuntu'
    name: 'ubuntu'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: ['cp', '-a', '.', '/persistent_volume']
#  - id: 'get-cache'
#    name: 'gcr.io/cloud-builders/gsutil'
#    volumes:
#      - name: 'vol1'
#        path: '/persistent_volume'
#    args: ['cp', '/persistent_volume/cache.tgz', 'gs://android-cloud-apk-builds/cache.tgz']
  # Run Lint
  - id: 'run-lint'
    name: 'gcr.io/cloud-builders/docker'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: ['run', '-v', 'vol1:/home/app', '--rm', 'us-docker.pkg.dev/android-devrel-ci/us.gcr.io/android-build:tag1', '/bin/sh', '-c', 'cd /home/app && ./gradlew :app:lintProdRelease']
  - id: 'save-cache'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-c'
      - |
        if [ -f $(< hashsum)-cache.tgz ]; then
          echo "Cache already exists, skipping build cache"
        else
          echo "Building new cache"
          tar zcf cache.tgz .gradle/caches .gradle/wrapper
        fi
  - id: 'save-cache'
    name: 'gcr.io/cloud-builders/gsutil'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: [ 'cp', '/persistent_volume/cache.tgz', 'gs://android-cloud-apk-builds/cache.tgz' ]

  # Upload Lint test results TODO: change test results bucket
  - id: 'upload-lint-results'
    name: 'gcr.io/cloud-builders/gsutil'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: ['cp', '/persistent_volume/app/build/reports/lint-results-prodRelease.html', 'gs://android-cloud-apk-builds/lint-results-prodRelease-$SHORT_SHA.html']
timeout: 7200s

#Runs all tasks
#args: ['run', '-v', 'vol1:/home/app', '--rm', 'us-docker.pkg.dev/android-devrel-ci/us.gcr.io/android-build:tag1', '/bin/sh', '-c', 'cd /home/app && ./gradlew :app:lintProdRelease :app-nia-catalog:lintRelease :lint:lint
#    testDemoDebug testProdDebug
#    packageDemoDebug packageDemoDebugAndroidTest']